#! /bin/bash

mvn clean compile assembly:single -Dhttp.useProxy=true -Dhttp.proxyHost=alpha01.tesoro.it -Dhttp.proxyPort=8080
FNS_JAR=$(ls target/*.jar)
echo FNS_JAR=$FNS_JAR
echo "java -Xmx1024m -Dfile.encoding=Cp1252 -jar $FNS_JAR \$@" 
echo "java -Xmx1024m -Dfile.encoding=Cp1252 -jar $FNS_JAR \$@" > start
