#! /bin/bash

#mvn clean compile assembly:single
#FNS_JAR= "$(ls target/ |grep .jar)"
FNS_JAR=$(ls target/*.jar)
#FNS_JAR= `ls target/ |grep .jar`
echo FNS_JAR=$FNS_JAR
echo "java -Xmx1024m -Dfile.encoding=Cp1252 -jar $FNS_JAR \$@" 
echo "java -Xmx1024m -Dfile.encoding=Cp1252 -jar $FNS_JAR \$@" > start

